adventureVersion=4.17.0
miniMessageVersion=4.17.0
hikariVersion=6.3.0
slf4jVersion=2.0.16
paperVersion=1.21.5-R0.1-SNAPSHOT
fabricMinecraftVersion=26.1
fabricLoaderVersion=0.19.2
fabricApiVersion=0.145.1+26.1
adventureFabricVersion=6.9.0
fabricMiniMessageVersion=4.26.1
fabricPermissionsVersion=0.7.0
