name: SimpleNicks
version: '${project.version}'
main: simplexity.simplenicks.SimpleNicks
authors: ['Rhythmic', 'Peashooter101']
api-version: 1.19
description: "A simple plugin to allow players to set and reset nicknames."
softdepend:
  - PlaceholderAPI
commands:
  nick:
    description: "Base command for SimpleNicks, Admin permission required to alter other's names."
    usage: "Usage: /nick [save|delete|set|reset|help|reload] <name> [player]"
    permission: simplenick.nick.set
