name: SimpleNicks
version: '${project.version}'
main: simplexity.simplenicks.SimpleNicks
authors: ['Rhythmic', 'Peashooter101']
api-version: 1.19
description: "A simple plugin to allow players to set and reset nicknames."
softdepend:
  - PlaceholderAPI
commands:
  nick:
    description: "Base command for SimpleNicks, Admin permission required to alter other's names."
    aliases: [simplenicks, simplenick, snick]
    usage: "Usage: /nick [save|delete|set|reset|help|reload] <name> [player]"
    permission: simplenick.nick.set
  snreload:
    description: "Reloads the config and locale of SimpleNicks."
    aliases: [simplenicksreload, simplenickreload, snreload]
    usage: "Usage: /snreload"
    permission: simplenick.reload
permissions:
  simplenick.admin:
    description: allows user to set and reset other players' nicknames
    default: op
    children:
      simplenick.nick: true
      simplenick.nick.set: true
  simplenick.admin.reset:
    default: op
    description: Allows the user to clear another player's nickname
    children:
        simplenick.admin: true
  simplenick.admin.restrictive:
    default: op
    description: Allows the user to set another player's nickname, but uses the formatting permissions of the other player
    children:
      simplenick.admin: true
  simplenick.admin.basic:
    default: op
    description: Allows the user to set another player's nickname, using the formatting permissions assigned to the player with the 'admin.basic' permission
    children:
      simplenick.admin: true
  simplenick.admin.full:
    default: false
    description: Allows the user to set another player's nickname, does not check the formatting permissions delegated to either player
    children:
      simplenick.admin: true
  simplenick.admin.save:
    default: op
    description: Allows the user to save another player's nickname for future use
    children:
      simplenick.admin: true
  simplenick.admin.delete:
    default: op
    description: Allows the user to delete one of another player's saved nicknames
    children:
      simplenick.admin: true
  simplenick.reload:
    description: allows a user to reload the locale and config of this plugin
    default: op
  simplenick.bypass.username:
    description: allows user to nickname themselves another person's username
    default: false
  simplenick.bypass.length:
    description: allows user to nickname themselves a username longer than the configured max characters
    default: false
  simplenick.bypass.regex:
    description: allows user to nickname themselves a username that does not match the configured regex
    default: false
  simplenick.nick:
    description: base of all formatting permissions
    default: op
  simplenick.nick.save:
    description: save your current nickname for future use, only works on 'FILE' save type
    default: op
    children:
      simplenick.nick: true
  simplenick.nick.delete:
    description: delete one of your previously saved nicknames
    default: op
    children:
      simplenick.nick: true
  simplenick.nick.set:
    description: allows usage of the /nick command
    default: op
    children:
      simplenick.nick: true
  simplenick.nick.reset:
    description: allows a user to reset their own nickname
    default: op
    children:
      simplenick.nick: true
  simplenick.nick.color:
    description: allows color codes to be used in a nickname
    default: op
    children:
      simplenick.nick: true
  simplenick.nick.gradient:
    description: allows gradients to be used in a nickname
    default: op
    children:
      simplenick.nick: true
  simplenick.nick.rainbow:
    description: allows the rainbow tag to be used in a nickname
    default: op
    children:
      simplenick.nick: true
  simplenick.nick.format.reset:
    description: allows the reset formatting tag to be used in a nickname
    default: op
    children:
      simplenick.nick: true
      simplenick.nick.format: true
  simplenick.nick.format.italic:
    description: allows the italic formatting tag to be used in a nickname
    default: op
    children:
      simplenick.nick: true
      simplenick.nick.format: true
  simplenick.nick.format.strikethrough:
    description: allows the strikethrough formatting tag to be used in a nickname
    default: op
    children:
      simplenick.nick: true
      simplenick.nick.format: true
  simplenick.nick.format.bold:
    description: allows the bold format tag to be used in a nickname
    default: op
    children:
      simplenick.nick: true
      simplenick.nick.format: true
  simplenick.nick.format.obfuscated:
    description: allows the obfuscated format tag to be used in a nickname
    default: op
    children:
      simplenick.nick: true
      simplenick.nick.format: true